package com.harium.suneidesis.knowledge.linguistic.core.nlp.pos;

/**
 * Tags borrowed from Penn Treebank/Nltk
 */
public enum Tag {
    COORDINATING_CONJUCTION,
    DETERMINER,
    EXISTENTIAL_THERE,
    FOREIGN_WORD,
    PREPOSITION,
    ADJECTIVE,
    ADJECTIVE_COMPARATIVE,
    ADJECTIVE_SUPERLATIVE,
    LIST_MARKER,
    MODAL,
    NOUN,
    NOUN_PLURAL,
    NOUN_PROPER,
    NOUN_PROPER_PLURAL,
    NUMERAL,// Cardinal Digit
    PREDETERMINER,
    POSSESSIVE,
    PERSONAL_PRONOUN,
    POSSESSIVE_PRONOUN,
    ADVERB,
    ADVERB_COMPARATIVE,
    ADVERB_SUPERLATIVE,
    PARTICLE,
    SYMBOL,
    CURRENCY,// Financial Symbol
    SUBORDINATING_CONJUCTION,
    TO,
    INTERJECTION,
    VERB,
    VERB_PAST_TENSE,
    VERB_GERUND,
    VERB_PAST_PARTICIPLE,
    VERB_PRESENT,
    VERB_PRESENT_THIRD_PERSON,
    WH_DETERMINER,
    WH_PRONOUN,
    WH_POSSESSIVE_PRONOUN,
    WH_ADVERB,
    PUNCTUATION,
    UNKNOWN
}
